import { DEMO_INVESTOR } from "@/lib/investor";

export const samplePortfolio = {
  investorName: DEMO_INVESTOR.name,
  panMasked: "ABCPS****K",
  statementDate: "March 2026",
  totalInvested: 850000,
  currentValue: 1120000,
  totalGain: 270000,
  gainPercent: 31.76,
  overallXIRR: 18.4,
  portfolioHealthScore: 72,
  riskProfile: "moderate",
  funds: [
    {
      name: "Mirae Asset Large Cap Fund - Direct Growth",
      amc: "Mirae Asset",
      category: "Large Cap",
      invested: 200000,
      currentValue: 274000,
      units: 1842.3,
      nav: 148.7,
      xirr: 19.2,
      expenseRatio: 0.54,
      overlapScore: 82,
      allocationPercent: 24.5,
      recommendation: "hold",
      recommendationReason: "Strong performer but high overlap with Axis Bluechip",
    },
    {
      name: "Axis Bluechip Fund - Direct Growth",
      amc: "Axis",
      category: "Large Cap",
      invested: 180000,
      currentValue: 221000,
      units: 3210.5,
      nav: 68.8,
      xirr: 14.1,
      expenseRatio: 0.47,
      overlapScore: 82,
      recommendation: "exit",
      allocationPercent: 19.7,
      recommendationReason: "87% stock overlap with Mirae Asset Large Cap makes this allocation redundant.",
    },
    {
      name: "Parag Parikh Flexi Cap Fund - Direct Growth",
      amc: "PPFAS",
      category: "Flexi Cap",
      invested: 150000,
      currentValue: 228000,
      units: 2891.2,
      nav: 78.9,
      xirr: 22.8,
      expenseRatio: 0.63,
      overlapScore: 28,
      allocationPercent: 20.4,
      recommendation: "increase",
      recommendationReason: "Best performer, low overlap, and diversified exposure including international holdings.",
    },
    {
      name: "SBI Nifty 50 Index Fund - Direct Growth",
      amc: "SBI",
      category: "Index",
      invested: 120000,
      currentValue: 157000,
      units: 7241.8,
      nav: 21.7,
      xirr: 17.6,
      expenseRatio: 0.1,
      overlapScore: 45,
      allocationPercent: 14,
      recommendation: "increase",
      recommendationReason: "Lowest-cost core exposure and a cleaner replacement for overlapping active large-cap funds.",
    },
    {
      name: "Axis Long Term Equity Fund - ELSS Direct Growth",
      amc: "Axis",
      category: "ELSS",
      invested: 100000,
      currentValue: 134000,
      units: 5120.4,
      nav: 26.2,
      xirr: 16.3,
      expenseRatio: 0.72,
      overlapScore: 61,
      allocationPercent: 12,
      recommendation: "hold",
      recommendationReason: "Lock-in and tax benefit under Section 80C still justify holding.",
    },
    {
      name: "Nippon India Small Cap Fund - Direct Growth",
      amc: "Nippon",
      category: "Small Cap",
      invested: 100000,
      currentValue: 106000,
      units: 1089.4,
      nav: 97.3,
      xirr: 8.2,
      expenseRatio: 0.68,
      overlapScore: 18,
      allocationPercent: 9.5,
      recommendation: "hold",
      recommendationReason: "Short-term underperformance, but still reasonable as a long-duration satellite allocation.",
    },
  ],
  insights: [
    {
      type: "warning",
      title: "High Fund Overlap Detected",
      description:
        "Mirae Asset Large Cap and Axis Bluechip share 87% of their top holdings. You are effectively paying duplicate active fees.",
    },
    {
      type: "warning",
      title: "Large Cap Overexposure",
      description:
        "44% of your portfolio is concentrated in large-cap strategies. A lower-cost index core would improve efficiency.",
    },
    {
      type: "success",
      title: "PPFAS is Your Star Performer",
      description:
        "Parag Parikh Flexi Cap has delivered 22.8% XIRR and adds differentiated exposure versus the rest of the portfolio.",
    },
    {
      type: "info",
      title: "Expense Ratio Drag",
      description:
        "You are paying Rs8,240 per year in fund fees. A measured shift toward index exposure could save roughly Rs4,100 annually.",
    },
  ],
  rebalancingPlan: {
    summary:
      "Your portfolio is fundamentally healthy, but large-cap overlap is diluting efficiency. Two decisive changes and one supporting tweak would improve diversification and lower cost.",
    urgency: "high",
    actions: [
      {
        action: "Exit",
        fund: "Axis Bluechip Fund",
        reason: "87% overlap with Mirae Asset Large Cap makes this the clearest redundancy in the portfolio.",
        priority: "high",
      },
      {
        action: "Increase allocation",
        fund: "SBI Nifty 50 Index Fund",
        reason: "A low-cost index core can replace overlapping active large-cap exposure with lower fees.",
        priority: "high",
      },
      {
        action: "Increase SIP",
        fund: "Parag Parikh Flexi Cap Fund",
        reason: "Strong risk-adjusted returns and differentiated holdings make it the best candidate for fresh money.",
        priority: "medium",
      },
    ],
    expectedImpact:
      "Projected XIRR improvement: +2.1% annually. Estimated additional corpus in 10 years: Rs3.8 lakhs.",
    estimatedAnnualSavings: 4100,
  },
  expenseDragAnnual: 8240,
  overlapMatrix: [
    { fund1: "Mirae Asset Large Cap", fund2: "Axis Bluechip", overlapPercent: 87 },
    { fund1: "Axis Bluechip", fund2: "Axis ELSS", overlapPercent: 61 },
    { fund1: "Mirae Asset Large Cap", fund2: "SBI Nifty 50", overlapPercent: 45 },
  ],
  benchmarkComparison: {
    portfolioReturn: 18.4,
    nifty50Return: 14.2,
    alpha: 4.2,
  },
  diversificationScore: 68,
  topHoldings: [
    { stock: "HDFC Bank", totalExposurePercent: 14.2 },
    { stock: "Infosys", totalExposurePercent: 11.8 },
    { stock: "Reliance Industries", totalExposurePercent: 10.4 },
    { stock: "ICICI Bank", totalExposurePercent: 9.7 },
    { stock: "TCS", totalExposurePercent: 8.3 },
  ],
};
